#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["package-github-dwh-blue", "blue"]
#
# [tool.uv.sources]
# package-github-dwh-blue = { git = "https://github.com/getcolors/github-dwh.git", rev = "56c9fb0e8bc1c8a967e0c71a896730be6ea5b0cc" }
# blue = { git = "https://github.com/getcolors/blue.git", rev = "369c5aafea790a03b649b3513003651e672f3f57" }
# ///
import os
os.environ.setdefault("GITHUB_DWH_PACKAGE_REVISION", "56c9fb0e8bc1c8a967e0c71a896730be6ea5b0cc")
from package_github_dwh_blue import exec, run
__all__ = ["run"]
if __name__ == "__main__": exec()
