#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["package-github-dwh-blue", "blue"]
#
# [tool.uv.sources]
# package-github-dwh-blue = { git = "https://github.com/getcolors/github-dwh.git", rev = "a57ef70920ec1bd3c0fe25743320d773e40d03c7" }
# blue = { git = "https://github.com/getcolors/blue.git", rev = "290f313ead5ca162875c33a049c880da017eae09" }
# ///
import os
os.environ.setdefault("GITHUB_DWH_PACKAGE_REVISION", "a57ef70920ec1bd3c0fe25743320d773e40d03c7")
from package_github_dwh_blue import exec, run
__all__ = ["run"]
if __name__ == "__main__": exec()
